### ISSUE TITLE
Re: Memory leak while using DDP 

### ISSUE THREAD

**Issue by Zhreyu** [Smu-Tan/ZS-NMT-Variations#1]
Hey there, 
I came across the issue you posted on the Huggingface Transformers GitHub repository (https://github.com/huggingface/transformers/issues/16705), and I'm reaching out to inquire about any progress or resolution you've found regarding the matter.

**Comment by Smu-Tan** [comment]
> Hey there, I came across the issue you posted on the Huggingface Transformers GitHub repository ([huggingface/transformers#16705](https://github.com/huggingface/transformers/issues/16705)), and I'm reaching out to inquire about any progress or resolution you've found regarding the matter.

Hi, sorry that I cannot remember how exactly I solved it. I vaguely remember this can be fixed by setting some DDP configurations such as GPU rank, and world size. I would suggest you follow this nice [tutorial](https://github.com/PrincetonUniversity/multi_gpu_training/tree/main) step by step, especially the parts about setting rank and world size (see [here](https://github.com/PrincetonUniversity/multi_gpu_training/blob/d3ce416384ada9fb644dd083da6e0b9ecc974e7f/02_pytorch_ddp/mnist_classify_ddp.py#L127) ).
