### ISSUE TITLE
A question about languages of mBart50

### ISSUE THREAD

**Issue by speedcell4** [Smu-Tan/ZS-NMT-Variations#3]
Hi, I noticed that mBart50 does not cover some languages of EC40, and I also noticed you have uploaded [a file](https://github.com/Smu-Tan/ZS-NMT-Variations/blob/main/train-eval-baseline-scripts/training_scripts/mbart50/extend_mbart50.ipynb) to extend mBart50.

Does that mean you simply add a new language token for these languages? like adding `so` to cover Somali? But you didn't add any new tokens of these languages, is this understanding correct? So that means you rely on existing tokens in mBart vocabulary for tokenization?

**Comment by Smu-Tan** [comment]
> Hi, I noticed that mBart50 does not cover some languages of EC40, and I also noticed you have uploaded [a file](https://github.com/Smu-Tan/ZS-NMT-Variations/blob/main/train-eval-baseline-scripts/training_scripts/mbart50/extend_mbart50.ipynb) to extend mBart50.
> 
> Does that mean you simply add a new language token for these languages? like adding `so` to cover Somali? But you didn't add any new tokens of these languages, is this understanding correct? So that means you rely on existing tokens in mBart vocabulary for tokenization?

@speedcell4 As I mentioned before, mBart50 does NOT support all 40 languages in our EC40, therefore we need to expand a. vocabulary (language tags) and b. embedding weights for these unseen languages.

We add new language tags to specify language / translation directions. For example, we add a 'so' token in lang_dict for somali. 

For sub-word segmentation / tokenization, we do not expand the vocabulary (except language tag) since mBart50 utilizes the vocabulary of XLM-R which supports 100 languages, resulting in a huge size (250k) and including many types of writing scripts.
